10 PRINT "adding your bois please wait."
20 PRINT " "
30 th_exec "sudo adduser wolfierae"
40 th_exec "sudo addgroup wolfierae"
50 th_exec "sudo adduser dora"
60 th_exec "sudo addgroup dora"
70 th_exec "sudo adduser casper"
80 th_exec "sudo addgroup casper"
90 th_exec "sudo adduser underwood"
100 th_exec "sudo addgroup underwood"
110 th_exec "sudo adduser zcj"
120 th_exec "sudo addgroup zcj"
130 th_exec "sudo adduser gunpointg"
140 th_exec "sudo addgroup gunpointg"
150 sleep 2
160 PRINT " "
170 sleep 3
180 PRINT "your bois have been added!"
190 PRINT " "